# http://ingest.tips/2014/09/26/trying-to-decide-between-flume-and-kafka-try-both/
# http://blog.cloudera.com/blog/2014/11/flafka-apache-flume-meets-apache-kafka-for-event-processing/
# https://github.com/jholoman/fraud_demo

a1.sources = r1
a1.channels = c1
a1.sinks = k1

#
# SOURCE
#

a1.sources.r1.type = multiport_syslogtcp
a1.sources.r1.channels = c1

a1.sources.r1.host = 0.0.0.0
a1.sources.r1.ports = 10001 10002 10003

# eventSize: Maximum size of a single event line, in bytes
a1.eventSize = 2500

# keepFields: Setting this to true will preserve the Priority,
#             Timestamp and Hostname in the body of the event.
a1.keepFields = false

# charset.default: Default character set used while parsing
#                  syslog events into strings.
a1.charset.default = UTF-8

#
# CHANNEL
#

a1.channels.c1.type = memory
a1.channels.c1.capacity = 10000
a1.channels.c1.transactionCapacity = 1000

#
# SINK
#

a1.sinks.k1.type = org.apache.flume.sink.kafka.KafkaSink

# brokerList: The brokers the Kafka sink uses to discover topic partitions
#             formatted as a comma-separated list of hostname:port entries.
#             You do not need to specify the entire list of brokers but
#             Cloudera recommends that you specify at least two for HA.
a1.sink.k1.brokerList = 

# topic: The Kafka topic to which messages are published by default. If the
#        event header contains a topic field the event is published to the
#        designated topic, overriding the configured topic.
a1.sink.k1.topic = kaccess_logs

# batchSize: The number of messages to process in a single batch.
#            Specifying a larger batchSize can improve throughput
#            and increase latency.
a1.sink.k1.batchSize = 100

# requiredAcks: The number of replicas that must acknowledge a message before it is written successfully. Possible values are 0 (do not wait for an acknowledgement), 1 (wait for the leader to acknowledge only) and -1 (wait for all replicas to acknowledge). To avoid potential loss of data in case of a leader failure, set this to -1.
a1.sink.k1.requiredAcks = 1

a1.sink.k1.channel = c1
